"""Initial Migration

Revision ID: d8fc9a06cb11
Revises: 
Create Date: 2021-09-14 13:42:45.825109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8fc9a06cb11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='testing_pkey')
    )
    # ### end Alembic commands ###
